# Generated by Django 5.0.6 on 2026-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='shortlist_message',
            field=models.TextField(blank=True, help_text='Custom message for the shortlist email body. Leave blank to use the default message.'),
        ),
    ]
